// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TitleDeedManagementSystem.Data;

#nullable disable

namespace TitleDeedManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("AccountOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BranchSettingId")
                        .HasColumnType("int");

                    b.Property<string>("CIFNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LoanLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutstandingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AccountId");

                    b.HasIndex("BranchSettingId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            BranchName = "Head Office"
                        },
                        new
                        {
                            BranchId = 2,
                            BranchName = "Pune Branch"
                        },
                        new
                        {
                            BranchId = 3,
                            BranchName = "Nashik Branch"
                        });
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.BranchSettings", b =>
                {
                    b.Property<int>("BranchSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchSettingId"));

                    b.Property<string>("BranchAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Circle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BranchSettingId");

                    b.ToTable("BranchSettings");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Collateral", b =>
                {
                    b.Property<int>("CollateralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollateralId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CollateralCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollateralNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<decimal>("OutstandingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TitleDeedStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CollateralId");

                    b.HasIndex("AccountId");

                    b.ToTable("Collaterals");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.CompactorMaster", b =>
                {
                    b.Property<int>("CompactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompactorId"));

                    b.Property<int>("BranchSettingId")
                        .HasColumnType("int");

                    b.Property<string>("CompactorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CompactorId");

                    b.HasIndex("BranchSettingId");

                    b.ToTable("CompactorMaster", (string)null);
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignationId"));

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesignationId");

                    b.ToTable("Designations");

                    b.HasData(
                        new
                        {
                            DesignationId = 1,
                            DesignationName = "Assistant Manager"
                        },
                        new
                        {
                            DesignationId = 2,
                            DesignationName = "Deputy Manager"
                        },
                        new
                        {
                            DesignationId = 3,
                            DesignationName = "Chief Manager"
                        },
                        new
                        {
                            DesignationId = 4,
                            DesignationName = "AGM"
                        });
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.RackMaster", b =>
                {
                    b.Property<int>("RackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RackId"));

                    b.Property<int>("CompactorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RackNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RackId");

                    b.HasIndex("CompactorId");

                    b.ToTable("RackMaster", (string)null);
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Maker"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Checker"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Branch Admin"
                        });
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.TitleDeedEntry", b =>
                {
                    b.Property<int>("TitleDeedEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TitleDeedEntryId"));

                    b.Property<string>("CERSAIAssetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CersaiSatisfactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CersaiStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CollateralId")
                        .HasColumnType("int");

                    b.Property<int>("CompactorId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMFolioNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EMRegisterNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsTitleDeedAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RackId")
                        .HasColumnType("int");

                    b.Property<string>("TitleDeedNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TitledeedStatus")
                        .HasColumnType("int");

                    b.HasKey("TitleDeedEntryId");

                    b.HasIndex("CollateralId")
                        .IsUnique();

                    b.HasIndex("CompactorId");

                    b.HasIndex("RackId");

                    b.ToTable("TitleDeedEntry", (string)null);
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DesignationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Account", b =>
                {
                    b.HasOne("TitleDeedManagementSystem.Models.BranchSettings", "BranchSettings")
                        .WithMany("Accounts")
                        .HasForeignKey("BranchSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchSettings");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Collateral", b =>
                {
                    b.HasOne("TitleDeedManagementSystem.Models.Account", "Account")
                        .WithMany("Collaterals")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.CompactorMaster", b =>
                {
                    b.HasOne("TitleDeedManagementSystem.Models.BranchSettings", "BranchSettings")
                        .WithMany("Compactors")
                        .HasForeignKey("BranchSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchSettings");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.RackMaster", b =>
                {
                    b.HasOne("TitleDeedManagementSystem.Models.CompactorMaster", "Compactor")
                        .WithMany("Racks")
                        .HasForeignKey("CompactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compactor");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.TitleDeedEntry", b =>
                {
                    b.HasOne("TitleDeedManagementSystem.Models.Collateral", "Collateral")
                        .WithOne("TitleDeedEntry")
                        .HasForeignKey("TitleDeedManagementSystem.Models.TitleDeedEntry", "CollateralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TitleDeedManagementSystem.Models.CompactorMaster", "Compactor")
                        .WithMany("TitleDeedEntries")
                        .HasForeignKey("CompactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TitleDeedManagementSystem.Models.RackMaster", "Rack")
                        .WithMany("TitleDeedEntries")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collateral");

                    b.Navigation("Compactor");

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.User", b =>
                {
                    b.HasOne("TitleDeedManagementSystem.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TitleDeedManagementSystem.Models.Designation", "Designation")
                        .WithMany("Users")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Designation");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.UserRole", b =>
                {
                    b.HasOne("TitleDeedManagementSystem.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TitleDeedManagementSystem.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Account", b =>
                {
                    b.Navigation("Collaterals");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Branch", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.BranchSettings", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Compactors");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Collateral", b =>
                {
                    b.Navigation("TitleDeedEntry");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.CompactorMaster", b =>
                {
                    b.Navigation("Racks");

                    b.Navigation("TitleDeedEntries");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Designation", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.RackMaster", b =>
                {
                    b.Navigation("TitleDeedEntries");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TitleDeedManagementSystem.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
